apiVersion: cache.example.com/v1alpha1
kind: Broker
metadata:
  name: example-broker
spec:
  # Add fields here
  size: 1
  brokerImage: 2019liurui/rocketmq-broker:4.5.0-alpine
  nameServers:
  slavePerGroup: 1
  replicationMode: "ASYNC"
  imagePullPolicy: Always
  pod:
    resources:
      requests:
        cpu: 0.1
        memory: 256Mi
    persistentVolumeClaim:
      metadata:
        name: "broker-store-pvc"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard-resize
        resources:
          requests:
            storage: 8Gi
